user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
    max_length: 50
remember_me:
  checked: "1"
seed:
  male: 0
  female: 1
  min_age: 16
  max_age: 60
home:
  movies: 8
summary:
  title_en: 20
  title_vi: 25
error_status:
  internal: 500
admin:
  summary:
    movie:
      title: 40
